#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# standard pkgin update:
pkgin update
pkgin clean

# Clean up
echo "* Cleaning up."
rm -rf /root/*
rm -rf /tmp/*

# Prepare image for provisioning
sm-prepare-image -y
